### ISSUE TITLE
Liste mit allen Programmen

### ISSUE THREAD

**Issue by m0rph2k** [Pix---/ioBroker.tvspielfilm#12]
Hi
Ist es möglich alle Programme von einen Tag (00:00 - 23:59) bzw evtl. eine XY Tagesvorschau in ein Object zu speichern !?

LG

**Comment by Pix---** [comment]
Hallo,

der Adapter "übersetzt" nur die RSS-Feeds der Webseite von tvspielfilm in Objekte. Die Detail-Informationen zu Sendungen gibt es nur für den Feeds "jetzt" (eben aktuell), "heute2015" (für heute 20:15 Uhr) und "heute 2200" (für heute 22:00 Uhr). Es gibt nur eine Abfrage, es werden keine Daten an tvspielfilm gesendet. Somit ist keine Definition eines Zeitraums möglich.

Gruß
Pix
